services:

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: live
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - redis

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: live
    ports:
      - ${EXPOSED_PORT}:8080
    env_file:
      - .env
    depends_on:
      - server

  redis:
    image: redis:8
    restart: unless-stopped
    ports:
      - 6379:6379
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - redis-data:/data
      - ./database/redis.conf:/usr/local/etc/redis/redis.conf
      - ./database/users.acl:/usr/local/etc/redis/users.acl
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis-data: