worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream api_0 {
        server api-0:1234;
    }
    upstream api_1 {
        server api-1:1234;
    }
    upstream frontend_0 {
        server frontend-0:8080;
    }
    upstream frontend_1 {
        server frontend-1:8080;
    }

    server {
        # LIVE
        listen 80;

        location /api/v1/ {
            proxy_pass http://api_0/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://frontend_0;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        # IDLE - preview whichever colors are not currently live
        listen 81;

        location /api/ {
            proxy_pass http://api_1;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://frontend_1;
            proxy_set_header Host $host;
        }
    }
}
