sonar.projectName=Seccure Notes Backend
sonar.projectKey=secure-notes_secret

# Sources
sonar.sources=src
sonar.tests=src/tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.js,**/*.spec.js

sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPath=coverage/lcov.info

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**,\
  **/*.config.ts,\
  **/*.config.js,\
  **/migrations/**,\
  **/__mocks__/**
