name: Frontend Pipeline

run-name: ${{github.actor}} pushed frontend changes to main

on:
  push:
    branches: [main, production]
    paths:
      - "frontend/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  snyk:
    name: Linting| Snyk - Dependency Scan
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend
    permissions:
      contents: read
      security-events: write # required to upload SARIF to the Security tab

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependecies
        run: npm ci

      - name: Snyk - Scan open-source dependencies
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >-
            --severity-threshold=high
            --sarif-file-output=frontend/snyk.sarif
            --file=frontend/package.json

      - name: Upload Snyk SARIF To Github Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: frontend/snyk.sarif

      - name: Fail Pipeline on high/critical vulnerabilities found
        if: steps.snyk.outcome == 'failure'
        run: |
          echo "::error::Snyk found high or critical severity vulnerabilities."
          echo "::error::Check the Security tab for details and fix before merging"
          exit 1

  sonarqube:
    name: Linting| SonarQube - Static Analysis
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependecies
        run: npm ci

      - name: SonarQube scan
        run: npm run sonar:scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Check SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: frontend/.scannerwork/report-task.txt
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


 build:
    name: Build | Frontend Docker image
    needs: [snyk, sonarqube]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        run: |
          docker build \
            --target=live \
            -t fedil/securenotes-frontend:sha-${{ github.sha }} \
            -t fedil/securenotes-frontend:main \
            -t fedil/securenotes-frontend:latest \
            .

      - name: Save Docker Frontend Image as Tarball
        run: |
          docker save \
            fedil/securenotes-frontend:sha-${{ github.sha }} \
            fedil/securenotes-frontend:main \
            fedil/securenotes-frontend:latest \
            -o securenotes-frontend.tar
            
      - name: Upload Frontend Image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-img
          path: frontend/securenotes-frontend.tar

          
  deliver:
    name: Deliver | Push Frontend-img to DockerHub
    needs: [build]
    
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Download saved Frontend-Img Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-img
          path: frontend

      - name: Load Frontend-Img into Docker
        run: docker load -i securenotes-frontend.tar
    
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push fedil/securenotes-frontend:sha-${{ github.sha }}
          docker push fedil/securenotes-frontend:main
          docker push fedil/securenotes-frontend:latest


